cookiecutter:
  project_name: "{{ cookiecutter.project_slug }}"
  project_slug: "dbt_{{ cookiecutter.project_name.lower().replace(' ', '_') }}"
  dbt_version: "1.6.0"
  profile_name: "{{ cookiecutter.project_slug }}_profile"
  target_schema: "analytics"
  database: "your_database"
  threads: 4
  warehouse: "your_warehouse"

  _copy_without_render:
    - "models/**"
    - "seeds/**"
    - "snapshots/**"

  _template:
    - "{{ cookiecutter.project_slug }}/"

{{ cookiecutter.project_slug }}/:
  dbt_project.yml:
    """
    name: {{ cookiecutter.project_slug }}
    version: "1.0.0"
    config-version: 2
    profile: {{ cookiecutter.profile_name }}

    models:
      {{ cookiecutter.project_slug }}:
        staging:
          +materialized: view
        marts:
          +materialized: table
    """

  profiles.yml:
    """
    {{ cookiecutter.profile_name }}:
      target: dev
      outputs:
        dev:
          type: bigquery
          method: service-account
          project: {{ cookiecutter.database }}
          dataset: {{ cookiecutter.target_schema }}
          threads: {{ cookiecutter.threads }}
          keyfile: /path/to/service/account.json
    """

  models/:
    staging/:
      stg_orders.sql:
        """
        with orders as (
          select * from {{ source('raw', 'orders') }}
        )
        select * from orders
        """
    marts/:
      orders.sql:
        """
        select * from {{ ref('stg_orders') }}
        """

  macros/:
    get_fiscal_year.sql:
      """
      {% macro get_fiscal_year(date_column) %}
      extract(year from {{ date_column }} + interval '3 months')
      {% endmacro %}
      """

  tests/:
    unique_orders.sql:
      """
      select order_id
      from {{ ref('stg_orders') }}
      group by order_id
      having count(*) > 1
      """

  .gitignore:
    """
    /target
    /dbt_packages
    /logs
    .dbt
    """

  README.md:
    """
    # {{ cookiecutter.project_slug }}

    This is a cookiecutter template for a dbt project.
    """

  ci-cd/: 
    github-actions.yml:
      """
      name: dbt CI
      on: [push]
      jobs:
        run-tests:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v3
              with:
                python-version: '3.8'
            - name: Install dbt
              run: pip install dbt-bigquery
            - name: Run dbt tests
              run: dbt test
      """
